<?php 
    
    $url = $this->backUrl;
    if($url !== Null){
?>
    <a href="<?php echo WEB_PATH.$this->backUrl;?>">Click Here View Detail</a>
    <?php }?>

<div class="box">
<div class="heading"><h1>Upload File and Unzip</h1></div>
<div class="form_field">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('upload', array('action' => 'uploadnew')));
$form->prepare();
?>


<?php 
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formHidden($form->get('patient_id')) . PHP_EOL;
// Not Validate in form with zip_file
echo $this->formRow($form->get('zip_file')) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;
echo $this->formRow($form->get('descriptionkey')) . PHP_EOL;
echo $this->formRow($form->get('imgkey')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
</div>
</div>