<?php 
    
    $url = $this->backUrl;
    if($url !== Null){
?>
    <a href="<?php echo WEB_PATH.$this->backUrl;?>">Click Here View Detail</a>
    <?php }?>

<div class="box">
<div class="heading"><h1>Uploadstory File and Unzip</h1></div>
<div class="form_field">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('uploadstory', array('action' => 'uploadnew')));
$form->prepare();
?>


<?php 
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formRow($form->get('patient_id')) . PHP_EOL;
?>
<div class="control-group">
  <!-- <div class="controls label22"><p> <button class="btn btn-small" type="button">Add New Name Story</button></p></div> -->
  <div  class="controls label11" ><?php echo $this->formRow($form->get('story_id')) . PHP_EOL;?></div>
</div>

<?php

// Not Validate in form with zip_file
echo $this->formRow($form->get('zip_file')) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;
//echo $this->formRow($form->get('descriptionkey')) . PHP_EOL;

$template_content = $form->get('descriptionkey');
$tbl_template_content = $template_content->getOption('label');
$txt_template_content = $this->formTextarea($template_content);

?>
<div class="control-group">
		<label class="control-label" for=""><?php echo $tbl_template_content; //echo $this->translate($tbl_description, 'PerseedApplication');?></label>
		<div class="controls">
			<?php echo $txt_template_content ;?>
		</div>
	</div>
	
<?php 

echo $this->formRow($form->get('imgkey')) . PHP_EOL;
?>
<div class="control-group">
  <div class="controls label22"><p> <button class="btn btn-small" type="button">Add New Chapter</button></p></div>
  <div  class="controls label11" ><?php echo $this->formRow($form->get('extend_chapter_id')) . PHP_EOL;?></div>
</div>
<?php
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
</div>
</div>

<script type="text/javascript" src="<?php echo CKEDITOR_PATH;?>"></script>
<script type="text/javascript">
CKEDITOR.replace( 'descriptionkey', {
	width: "900px",
	height: "300px",
	toolbar: "Full"
} );
</script>
