<?php 
	$templateISUSS = $this->basePath('/Page_Bottom_Issus/');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>ALATCA - Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Le styles -->
    <link  href="<?php echo $templateISUSS; ?>css/bootstrap.css" rel="stylesheet">
    <link  href="<?php echo $templateISUSS; ?>font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
      <link rel="stylesheet"  href="<?php echo $templateISUSS; ?>css/font-awesome-ie7.min.css">
    <![endif]-->
    <link rel="stylesheet" type="text/css"  href="<?php echo $templateISUSS; ?>css/style.css" />
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="<?php echo $templateISUSS; ?>http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <script src="<?php echo $templateISUSS; ?>js/respond.src.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"  href="<?php echo $templateISUSS; ?>img/sample/logo-144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"  href="<?php echo $templateISUSS; ?>img/sample/logo-114.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72"  href="<?php echo $templateISUSS; ?>img/sample/logo-72.png">
                    <link rel="apple-touch-icon-precomposed"  href="<?php echo $templateISUSS; ?>img/sample/logo-57.png">
                                   <link rel="shortcut icon"  href="<?php echo $templateISUSS; ?>img/sample/logo.png">
    
  </head>

  <body>
  
    <div class="wrapper">
      <div class="row">
        <div class="col-md-3 sidebar">
          <div class="navbar" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#rebound-navbar-collapse"><span class="fa fa-bars"></span> Menu</button>
              <a  href="<?php echo $templateISUSS; ?>index.html" class="navbar-brand">Alatca Port CMS</a>
              <p class="brand-text">Editor - App Mobile.</p>
            </div><!-- end navbar-header -->
            <div class="collapse navbar-collapse" id="rebound-navbar-collapse">
              <ul class="nav navbar-nav">
              <?php require_once 'menu.php';?>
              
              </ul>
              <form class="navbar-form" role="search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search" value="" />
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="button"><span class="fa fa-search"></span></button>
                  </span>
                </div><!-- end input group -->
              </form><!-- end navbar-form -->
              <ul class="nav navbar-nav filter-portfolio">
                <li class="title">Work : sorted by topics</li>
                <li class="active"><a  href="#none" data-filter="*">All</a> <span>(123)</span></li>
                <li><a  href="#none" data-filter=".film">Film</a> <span>(9)</span></li>
                <li><a  href="#none" data-filter=".music">Music</a> <span>(22)</span></li>
                <li><a  href="#none" data-filter=".art">Art</a> <span>(7)</span></li>
                <li><a  href="#none" data-filter=".social">Social</a> <span>(49)</span></li>
              </ul>
              <ul class="nav navbar-nav nav-social hidden-sm hidden-xs">
                <li class="title">Social</li>
                <li><a  href="#none">Twitter</a></li>
                <li><a  href="#none">Facebook</a></li>
                <li><a  href="#none">LinkedIn</a></li>
                <li><a  href="#none">Dribbble</a></li>
              </ul>
            </div><!-- end navbar-collapse -->
          </div><!-- end navbar -->
        </div><!-- end col -->
        <div class="col-md-9 content">
          <div class="portfolio-wrapper">
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/sintel/sample-sintel-1.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/elephants-dream/sample-elephants-1.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Elephants Dream</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/big-buck-bunny/sample-bunny-1.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Big Buck Bunny</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/sintel/sample-sintel-2.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel Review</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/big-buck-bunny/sample-bunny-3.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Big Buck Bunny In CG Magazine From China</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/elephants-dream/sample-elephants-2.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Singapore, CGOverdrive And 3dsense</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/sintel/sample-sintel-3.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/big-buck-bunny/sample-bunny-2.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Studio Harddisk Online</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/elephants-dream/sample-elephants-3.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">High Frame Rate, 4K And Stereo 3D Release</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/sintel/sample-sintel-4.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="<?php echo $templateISUSS; ?>">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="<?php echo $templateISUSS; ?>">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/big-buck-bunny/sample-bunny-1.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Big Buck Bunny</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/elephants-dream/sample-elephants-2.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Elephants Dream</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film art">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/sintel/sample-sintel-3.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Sintel at Seattle International Film Festival</a></h2>
                <p>The cinema where Sintel screens has digital 4k projection, I’m working with them getting this formatted right and delivered. Would be a real ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Art</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card film social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/big-buck-bunny/sample-bunny-3.png" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">BBB Goes Hollywood!</a></h2>
                <p>A comedy about a fat rabbit taking revenge on three irritating rodents. The film - in the fastest imaginable 3D computer animation - almost seems...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Film</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
            <div class="card music social">
              <a  href="#" class="thumb">
                <img src="<?php echo $templateISUSS; ?>img/sample/elephants-dream/sample-elephants-1.jpg" alt="" title="" />
                <span class="overlay"><span class="fa fa-search"></span></span>
              </a>
              <div class="card-body">
                <h2><a  href="#">Elephants Dream</a></h2>
                <p>Elephants Dream is the world’s first open movie, made entirely with open source graphics software such as Blender , and with all production ...</p>
                <p><a  href="#">Read More</a></p>
              </div><!-- end card-body -->
              <div class="card-footer">
                <ul class="list-inline filters">
                  <li><a  href="#none">Music</a></li>
                  <li><a  href="#none">Social</a></li>
                </ul>
              </div><!-- end card-footer -->
            </div><!-- end card -->
          </div><!-- end portfolio-wrapper -->
          <div class="pagination-wrapper">
            <ul class="pagination">
              <li class="disabled"><span>Prev</span></li>
              <li class="active"><a  href="#none">1</a></li>
              <li><a  href="#none">2</a></li>
              <li><a  href="#none">3</a></li>
              <li><a  href="#none">4</a></li>
              <li><a  href="#none">5</a></li>
              <li><a  href="#none">Next</a></li>
            </ul>
          </div><!-- end pagination-wrapper -->
        </div><!-- end col -->
      </div><!-- end row -->
    </div><!-- end wrapper -->
    
    <footer class="hidden-xs">
      <p class="pull-left">&copy; Copyright 2014. Alatca.</p>
      <p class="pull-right"><a  href="#none">Alatca</a> by Alatca. <a  href="#<?php //echo $templateISUSS; ?>about">Abuot Us</a>.</p>
    </footer>
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="<?php echo $templateISUSS; ?>js/jquery.min.js"></script>
    <script src="<?php echo $templateISUSS; ?>js/bootstrap.js"></script>
    <script src="<?php echo $templateISUSS; ?>js/rebound.js"></script>
    <script src="<?php echo $templateISUSS; ?>js/jquery.isotope.min.js"></script>
    <script type="text/javascript">
      
      $(document).ready(function() {
        
        $('.dropdown-toggle').dropdown();
        
        var $container = $('.portfolio-wrapper');
        
        $container.imagesLoaded( function(){
          $container.isotope({
            itemSelector : '.card',
            layoutMode : 'fitRows'
          });
        });
        
        // Needed functions
        var getColWidth = function() {
          var width,
          windowWidth = $(window).width();
          if( windowWidth <= 480 ) {
            width = Math.floor( $container.width() );
          } else if( windowWidth <= 768 ) {
            width = Math.floor( $container.width() );
          } else {
            width = Math.floor( 250 );
          }
          return width;
        }

        function setWidths() {
          var colWidth = getColWidth();
          $container.children().css({ width: colWidth });
        }

    
        $(window).smartresize(function() {
          setWidths();
          $container.isotope({
            masonry: {
              columnWidth: getColWidth()
            }
          });
        });
        
        $('.filter-portfolio li a').click(function(){
          $('.filter-portfolio li.active').removeClass('active');
          $(this).parent('li').addClass('active');
          var selector = $(this).attr('data-filter');
          $container.isotope({
            filter: selector,
            masonry: {  }
          });
          return false;
        });
        // update columnWidth on window resize
        $(window).smartresize(function(){
          $container.isotope({
            // update columnWidth to a percentage of container width
            masonry: {  }
          });
        });
        
      });
      
    </script>

  </body>
</html>
