<?php
$title = 'Delete magazinevietnam';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p> <h3 style="color: red;font-style: italic;text-align: center;">Are you sure that you want to delete .If you delete the data related to it will be deleted and can not be recovered ?</h3></p>
<?php 
$url = $this->url('magazinevietnam', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$magazinevietnam->id; ?>" />
  <input type="submit" name="del" value="Yes" class="btn btn-primary" />
  <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>
