<?php 
	$Editorapp = $this->basePath('/editorapp/');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Alatca Editor</title>
<link href="<?php echo $Editorapp ; ?>style1.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $Editorapp ; ?>css.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php echo $Editorapp ; ?>css/bootstrap.min.css"  />
<script type="text/javascript" src="<?php echo $Editorapp ; ?>js/jquery-1.6.3.min.js"></script>
<script type="text/javascript" src="<?php echo $Editorapp ; ?>js/main.js"></script>
<link rel="stylesheet" href="<?php echo $Editorapp ; ?>css/bootstrap-theme.min.css" />
</head>

<body>	
       <header>
            <div class="container-fluid">
                    <nav class="navbar navbar-default" role="navigation">
                          
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                              </button>
                              <a class="navbar-brand logo" href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/logo.png" alt="logo" /></a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                              <ul class="nav navbar-nav">
                                <li class="active"><a href="<?php echo $Editorapp ; ?>"><img src="<?php echo $Editorapp ; ?>images/h4.png" alt="h4" /></a></li>
                                <li class="dt-active"><a href="<?php echo $Editorapp ; ?>"><img src="<?php echo $Editorapp ; ?>images/h3-2.png" alt="h3" /></a></li>
                                <li><p>Page:</p></li>
                                <li class="dropdown">
                                  <a href="<?php echo $Editorapp ; ?> #" class="dropdown-toggle" data-toggle="dropdown">Home<b class="caret"></b></a>
                                  <ul class="dropdown-menu">
                                    <li><a href="<?php echo $Editorapp ; ?>">Home</a></li>
                                    <li><a href="<?php echo $Editorapp ; ?>">About</a></li>
                                    <li><a href="<?php echo $Editorapp ; ?>">Contact</a></li>
                                  </ul>
                                </li>
                              </ul>
                              
                              <ul class="nav navbar-nav navbar-right">
                              		<li>
                                        <button type="button" class="btn btn-default undo-righ" data-toggle="tooltip" data-placement="bottom" title="Undo Ctrl+Z"></button>  
                                        <button type="button" class="btn btn-default redo-right" data-toggle="tooltip" data-placement="bottom" title="Redo Ctrl + Y"></button> 
                                        <button type="button" class="btn btn-default rulers-right" data-toggle="tooltip" data-placement="bottom" title="Rulers and Guides"></button> 
                                        <button type="button" class="btn btn-default gril-right" data-toggle="tooltip" data-placement="bottom" title="Gridlines"></button> 
                                        <button type="button" class="btn btn-default snap-right" data-toggle="tooltip" data-placement="bottom" title="Snap to Objects"></button> 
                                        <button type="button" class="btn btn-default layout-right" data-toggle="tooltip" data-placement="bottom" title="Layout editor files"></button>
                                        <button type="button" class="btn btn-default edit-right" data-toggle="tooltip" data-placement="bottom" title="edit"></button>
                                        <button type="button" class="btn btn-default save-right" data-toggle="tooltip" data-placement="bottom" title="Save template"></button>
                                        <button type="button" class="btn btn-default share-right" data-toggle="tooltip" data-placement="bottom" title="Share"></button>
                                        <button type="button" class="btn btn-default download-right" data-toggle="tooltip" data-placement="bottom" title="Downloading"></button>
                                        <button type="button" class="btn btn-default delete-right" data-toggle="tooltip" data-placement="bottom" title="Delete"></button>
                                     </li>
                                     <li>   
                                        <button type="button" class="btn btn-default Preview-righ" data-toggle="tooltip" data-placement="bottom" title="Check out your site before you Publish">Preview</button>  
                                        <button type="button" class="btn btn-default Save-right" data-toggle="tooltip" data-placement="bottom" title="Save a draft">Save</button> 
                                        <button type="button" class="btn btn-default Publish-right" data-toggle="tooltip" data-placement="bottom" title="Publish online">Publish</button> 
                                        <button type="button" class="btn btn-default Upgrade-right" data-toggle="tooltip" data-placement="bottom" title=" Upgrade to add your own personal web address">Upgrade</button> 
                                        <button type="button" class="btn btn-default help-right"></button>
                                     </li>   
                              </ul>
                            </div><!-- /.navbar-collapse -->
                          
                        </nav>
		</div><!-- /.container-fluid -->
       		
       </header>
       <div class="clear"></div>
       <div class="content">
       		<div class="container-fluid">

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 wrapper" id="tabContaier">
                  <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 ul-content">
                      <ul class="nav nav-list nav-el-ez tab_nav clearfix">
                          <li class="page-topprin"><a href ="#tab_1"></a></li>
                          <li class="design-topprin"><a href ="#tab_2"></a></li>
                          <li class="add-topprin"><a href ="#tab_3"></a></li>
                          <li class="app-topprin"><a href ="#tab_4"></a></li>
                          <li class="setting-topprin"><a href="#tab_5"></a></li>
                      </ul>
                  </div>
                  <div id="tab_1" class="col-lg-3 col-md-4 col-sm-5 col-xs-9 tab_content">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ul-center-content-page">
                                        <div class="center-tabs-page">
                                           <div class="service service-1-page">
                                                <div class="cn-content-page" >
                                                      <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> Pages </h3>
                                                      <div class="clear"></div>
                                                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 c-content-page">
                                                          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-bosung-page">
                                                              <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-note-page"> Navigate through your pages. To rename a page, click the wheel icon.</p>                     
                                                              <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-drag-page">Drag pages up/down to reorder</p>
                                                              <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-righ-page">Drag pages up/down to reorder</p>
                                                              <a data-toggle="modal" data-target="#myModal" href="<?php echo $Editorapp ; ?>">Learn More</a>
                                                          </div>
                                                          <div class="clear"></div>
                                                          <div class="scrollbar">
                                                              <ul class="nav bs-docs-sidenav-page"> 
                                                                    <li class="nav-home-page"><a href="<?php echo $Editorapp ; ?>">Home <i class="setting-page"></i></a></li>
                                                                    <li><a href="<?php echo $Editorapp ; ?> #">About <b class="caret"></b><i class="setting-page"></i></a>
                                                                         <ul class="nav sidenav-trong">
                                                                            <li><a href="<?php echo $Editorapp ; ?> #">PRESS <i class="setting-page"></i></a></li>
                                                                            <li><a href="<?php echo $Editorapp ; ?> #">PRESS 12 <i class="setting-page"></i></a></li>
                                                                        </ul>
                                                                    </li>
                                                                    <div class="clear"></div>
                                                                    <li><a href="<?php echo $Editorapp ; ?>">menu <i class="setting-page"></i></a></li>
                                                                    <li><a href="<?php echo $Editorapp ; ?>">contact <i class="setting-page"></i></a></li>
                                                                     <li><a href="<?php echo $Editorapp ; ?>">menu <i class="setting-page"></i></a></li>
                                                                    <li><a href="<?php echo $Editorapp ; ?>">contact <i class="setting-page"></i></a></li>
                                                                    <li><a href="<?php echo $Editorapp ; ?>">menu <i class="setting-page"></i></a></li>
                                                                    <li><a href="<?php echo $Editorapp ; ?>">contac <i class="setting-page"></i>t</a></li>
                                                                     <li><a href="<?php echo $Editorapp ; ?>">menu <i class="setting-page"></i></a></li>
                                                                    <li><a href="<?php echo $Editorapp ; ?>">contact <i class="setting-page"></i></a></li>
                                                              </ul>
                                                          </div>
                                                          <div class="clear"></div>
                                                          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 add-page-page"><a href="<?php echo $Editorapp ; ?>">Add page </a></div>
                                                          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 setting-seo-page"><a href="<?php echo $Editorapp ; ?>">Settings and SEO</a></div>
                                                          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-Page-transtions">
                                                                <div class="col-lg-11 col-md-11 col-sm-11 col-xs-11 gh-transtions"><p>Page transtions</p></div>
                                                                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 link-transtions"><a href="<?php echo $Editorapp ; ?>">?</a></div>
                                                                
                                                          </div>
                                                          
                                                          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 btn-group-page">
                                                                  <select class="selectpicker" data-header="Select a condiment">
                                                                            <option>Swipe Horizontal</option>
                                                                            <option>Swipe Vertical</option>
                                                                            <option>Cross Fade</option>
                                                                            <option>Out-In</option>
                                                                  </select>
                                                          </div>
                                                          
                                                    <div class="clear"></div>  
                                                      </div>
                                                    <div class="clear"></div>
                                                    
                                               </div>
                                              </div>
                                          </div>
                                     </div>
                  </div>
                  <div id="tab_2" class="col-lg-3 col-md-4 col-sm-5 col-xs-9 tab_content">
                                 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ul-center-content-design">
                                    <div class="center-tabs-design">
                                       <div class="service service-1-design">
                                            <div class="cn-content-design" >
                                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> Design </h3>
                                                  <div class="clear"></div>
                                                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 c-content-design">
                                                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-bosung-design">
                                                          <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-note-design">Play with the design tools to make your site look exactly how you want.</p>                     
                                                          <a data-toggle="modal" data-target="#myModal" href="<?php echo $Editorapp ; ?>">Learn More</a>
                                                      </div>
                                                      <div class="clear"></div>
                                                      <div id="scrollbar-bs-docs-sidenav-design">
                                                          <div class="panel-group" id="accordion">
                                                            <div class="panel panel-default">
                                                              <div class="panel-heading">
                                                                <h4 class="panel-title">
                                                                  <a data-toggle="collapse" data-parent="#accordion" href="<?php echo $Editorapp ; ?> #collapseOne" class="li-setting-background" >
                                                                    BACKGROUND
                                                                    <i class="setting-design"></i>
                                                                  </a>
                                                                    
                                                                </h4>
                                                              </div>
                                                              <div id="collapseOne" class="panel-collapse collapse in">
                                                                <div class="panel-body">
                                                                    <div class="background-desig-top">
                                                                        <div class="info-background-design">
                                                                            <p>Select a background below or choose to Upload your own image. You can also click Customize Background and make changes to get your exact look & feel.</p>
                                                                        </div>
                                                                        <div class="lear-more-background-design">
                                                                            <a href="<?php echo $Editorapp ; ?>">Learn More</a>
                                                                        </div>
                                                                        <div class="button-top-background-design">
                                                                                <button type="button" class="btn btn-info">Upload & Customize Background</button>
                                                                        </div>
                                                                    </div>
                                                                    <div class="background-desig-center">
                                                                        <div class="scrollbar chon-background">
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m1.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m2.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m3.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m4.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m5.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m6.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m7.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m8.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m9.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m10.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m11.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m12.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m13.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m14.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m15.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m16.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m17.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m18.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m19.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m20.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m21.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m22.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m23.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m24.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m25.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m26.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m27.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 background-design-one">
                                                                                <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/m28.png" class="img-responsive" alt="Responsive image" /></a>
                                                                            </div>
                                                                            
                                                                            
                                                                        </div>
                                                                        <div class="nut-chon-background">
                                                                            <button type="button" class="btn btn-info">Discard Changes</button>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                              </div>
                                                            </div>
                                                            <div class="panel panel-default">
                                                              <div class="panel-heading">
                                                                <h4 class="panel-title">
                                                                  <a data-toggle="collapse" data-parent="#accordion" href="<?php echo $Editorapp ; ?> #collapseTwo" class="li-setting-colors">
                                                                    Colors
                                                                    <i class="setting-design"></i>
                                                                  </a>
                                                                </h4>
                                                              </div>
                                                              <div id="collapseTwo" class="panel-collapse collapse">
                                                                <div class="panel-body">
                                                                    <div class="background-desig-top">
                                                                        <div class="info-background-design">
                                                                            <p>Choose a color palette to instantly transform your site. To per sonalize your color palette, select Customize Palette.</p>
                                                                        </div>
                                                                        <div class="lear-more-background-design">
                                                                            <a href="<?php echo $Editorapp ; ?> #">Learn More</a>
                                                                        </div>
                                                                        <div class="clear"></div>
                                                                        <div class="button-top-color-design">
                                                                                <button type="button" class="btn btn-info">Customize Palette</button>
                                                                        </div>
                                                                    </div>
                                                                    
                                                                    <div class="background-desig-center">
                                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 scrollbar chon-background">
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 chon-color-left">
                                                                                    <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/color1.jpg" class="img-responsive" alt="Responsive image" /></a>
                                                                                </div>
                                                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 chon-color-right">
                                                                                    <a href="<?php echo $Editorapp ; ?> #">Lets Hear It For The Boys</a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 chon-color-left">
                                                                                    <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/color2.jpg" class="img-responsive" alt="Responsive image" /></a>
                                                                                </div>
                                                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 chon-color-right">
                                                                                    <a href="<?php echo $Editorapp ; ?> #">I See Red</a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 chon-color-left">
                                                                                    <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/color3.jpg" class="img-responsive" alt="Responsive image" /></a>
                                                                                </div>
                                                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 chon-color-right">
                                                                                    <a href="<?php echo $Editorapp ; ?> #">Im a Bumble Bee</a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 chon-color-left">
                                                                                    <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/color1.jpg" class="img-responsive" alt="Responsive image" /></a>
                                                                                </div>
                                                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 chon-color-right">
                                                                                    <a href="<?php echo $Editorapp ; ?> #">Lets Hear It For The Boys</a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 chon-color-left">
                                                                                    <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/color2.jpg" class="img-responsive" alt="Responsive image" /></a>
                                                                                </div>
                                                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 chon-color-right">
                                                                                    <a href="<?php echo $Editorapp ; ?> #">I See Red</a>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 chon-color-left">
                                                                                    <a href="<?php echo $Editorapp ; ?> #"><img src="<?php echo $Editorapp ; ?>images/color3.jpg" class="img-responsive" alt="Responsive image" /></a>
                                                                                </div>
                                                                                <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 chon-color-right">
                                                                                    <a href="<?php echo $Editorapp ; ?> #">Im a Bumble Bee</a>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="nut-chon-background">
                                                                            <button type="button" class="btn btn-info">Discard Changes</button>
                                                                        </div>
                                                                    </div>
                                                                    
                                                                    
                                                                    
                                                                    
                                                                    
                                                                </div>
                                                              </div>
                                                            </div>
                                                            <div class="panel panel-default">
                                                              <div class="panel-heading">
                                                                <h4 class="panel-title">
                                                                    <a data-toggle="collapse" data-parent="#accordion" href="<?php echo $Editorapp ; ?> #collapseThree" class="li-setting-fonts">
                                                                    Fonts
                                                                    <i class="setting-design"></i>
                                                                  </a>
                                                                </h4>
                                                              </div>
                                                              <div id="collapseThree" class="panel-collapse collapse">
                                                                <div class="panel-body">
                                                                    <div class="background-desig-top">
                                                                        <div class="info-background-design">
                                                                            <p>Transform your site's font scheme in one click. To personalize click Customize Fonts.</p>
                                                                        </div>
                                                                        <div class="lear-more-background-design">
                                                                            <a href="<?php echo $Editorapp ; ?> #">Learn More</a>
                                                                        </div>
                                                                        <div class="clear"></div>
                                                                        <div class="button-top-color-design">
                                                                                <button type="button" class="btn btn-info">Customize Fonts</button>
                                                                        </div>
                                                                    </div>
                                                                    
                                                                    <div class="background-desig-center">
                                                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 scrollbar chon-background">
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                    <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                    <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div comp="wysiwyg.editor.components.inputs.font.FontPresetSelector" skin="wysiwyg.editor.skins.inputs.font.FontPresetSelectorSkin" id="FntPrstSlctr1-xcu" styleid="" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin focusable " tabindex="0" style="visibility: visible;" state="up">
                                                                                    <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                        <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                        <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>

                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div comp="wysiwyg.editor.components.inputs.font.FontPresetSelector" skin="wysiwyg.editor.skins.inputs.font.FontPresetSelectorSkin" id="FntPrstSlctr1-xcu" styleid="" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin focusable " tabindex="0" style="visibility: visible;" state="up">
                                                                                    <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                        <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                        <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>

                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div comp="wysiwyg.editor.components.inputs.font.FontPresetSelector" skin="wysiwyg.editor.skins.inputs.font.FontPresetSelectorSkin" id="FntPrstSlctr1-xcu" styleid="" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin focusable " tabindex="0" style="visibility: visible;" state="up">
                                                                                    <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                        <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                        <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>

                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div comp="wysiwyg.editor.components.inputs.font.FontPresetSelector" skin="wysiwyg.editor.skins.inputs.font.FontPresetSelectorSkin" id="FntPrstSlctr1-xcu" styleid="" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin focusable " tabindex="0" style="visibility: visible;" state="up">
                                                                                    <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                        <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                        <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>

                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div comp="wysiwyg.editor.components.inputs.font.FontPresetSelector" skin="wysiwyg.editor.skins.inputs.font.FontPresetSelectorSkin" id="FntPrstSlctr1-xcu" styleid="" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin focusable " tabindex="0" style="visibility: visible;" state="up">
                                                                                    <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                        <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                        <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>

                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 chon-colors">
                                                                                <div comp="wysiwyg.editor.components.inputs.font.FontPresetSelector" skin="wysiwyg.editor.skins.inputs.font.FontPresetSelectorSkin" id="FntPrstSlctr1-xcu" styleid="" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin focusable " tabindex="0" style="visibility: visible;" state="up">
                                                                                    <div class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-c-fontButton">
                                                                                        <div skinpart="label" class="wysiwyg_editor_skins_inputs_font_FontPresetSelectorSkin-label" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 22px; line-height: 1.4em; font-family: lobster, cursive;">The Little Prince</div>
                                                                                        <div skinpart="paragraph" style="font-style: normal; font-variant: normal; font-weight: bold; font-size: 14px; line-height: 1.4em; font-family: 'open sans', sans-serif;">Let them eat cake</div>

                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="nut-chon-background">
                                                                            <button type="button" class="btn btn-info">Discard Changes</button>
                                                                        </div>
                                                                    </div>
                                                                    
                                                                    
                                                                </div>
                                                              </div>
                                                            </div>
                                                        </div>
                                                      </div>
                                                <div class="clear"></div>  
                                                </div>
                                                <div class="clear"></div>
                                           </div>
                                           
                                          </div>
                                    </div>
                                </div>
                 </div>
                  <div id="tab_3" class="col-lg-3 col-md-4 col-sm-5 col-xs-9 tab_content">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ul-center-content-add">
                                <div class="center-tabs-add">
                                   <div class="service service-1-add">
                                        <div class="cn-content-add">
                                              <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> Add </h3>
                                              <div class="clear"></div>
                                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 c-content-add">
                                                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-bosung-add">
                                                      <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-note-add">Choose the elements you'd like to add to your site.</p>                     
                                                      <a data-toggle="modal" data-target="#myModal" href="<?php echo $Editorapp ; ?> #">Learn More</a>
                                                  </div>
                                                  <div class="clear"></div>
                                                  <div class="scrollbar scrollbar-add">
                                                      <ul class="nav bs-docs-sidenav-add"> 
                                                            <li class="nav-home-add"><a href="<?php echo $Editorapp ; ?> #" class="li-setting-text"> Text<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-imgage">Image<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-gallery">Gallery<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-media">Media<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-shapes">Shapes & Lines<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-button">Buttons & Menus<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-blog">Blog<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-online">Online Store<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-sicial">Social<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-apps">Apps<i class="setting-add"></i></a></li>
                                                            <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-list-buil">List Builder<i class="setting-add"></i></a></li>
                                                      </ul>
                                                  </div>
                                            <div class="clear"></div>  
                                            </div>
                                            <div class="clear"></div>
                                       </div>
                                      </div>
                                </div>
                            </div>
                  </div>
                  <div id="tab_4" class="col-lg-3 col-md-4 col-sm-5 col-xs-9 tab_content">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ul-center-content-setting">
                                    <div class="center-tabs-setting">
                                       <div class="service service-1-setting">
                                            <div class="cn-content-setting">
                                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> Settings </h3>
                                                  <div class="clear"></div>
                                                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 c-content-setting">
                                                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-bosung-setting">
                                                          <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-note-setting">Change your site settings including SEO and statistics.</p>                     
                                                          <a data-toggle="modal" data-target="#myModal" href="<?php echo $Editorapp ; ?> #">Learn More</a>
                                                      </div>
                                                      <div class="clear"></div>
                                                      <div class="scrollbar-setting">
                                                          <ul class="nav bs-docs-sidenav-setting"> 
                                                                <li class="nav-home-setting"><a href="<?php echo $Editorapp ; ?> #" class="li-setting-site-address"> Site Address<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-seo-google">SEO(Google)<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-social-setting">Social Settings<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-statis">Statistics<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-favicon">Favicon<i class="setting-setting"></i></a></li>
                                                          </ul>
                                                      </div>
                                                <div class="clear"></div>  
                                                </div>
                                                <div class="clear"></div>
                                           </div>
                                          </div>
                                    </div>
                                </div>
                </div>
                <div id="tab_5" class="col-lg-3 col-md-4 col-sm-5 col-xs-9 tab_content">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ul-center-content-setting">
                                    <div class="center-tabs-setting">
                                       <div class="service service-1-setting">
                                            <div class="cn-content-setting">
                                                  <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> Settings </h3>
                                                  <div class="clear"></div>
                                                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 c-content-setting">
                                                      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-bosung-setting">
                                                          <p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-note-setting">Change your site settings including SEO and statistics.</p>                     
                                                          <a data-toggle="modal" data-target="#myModal" href="<?php echo $Editorapp ; ?> #">Learn More</a>
                                                      </div>
                                                      <div class="clear"></div>
                                                      <div class="scrollbar-setting">
                                                          <ul class="nav bs-docs-sidenav-setting"> 
                                                                <li class="nav-home-setting"><a href="<?php echo $Editorapp ; ?> #" class="li-setting-site-address"> Site Address<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-seo-google">SEO(Google)<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-social-setting">Social Settings<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-statis">Statistics<i class="setting-setting"></i></a></li>
                                                                <li><a href="<?php echo $Editorapp ; ?> #" class="li-setting-favicon">Favicon<i class="setting-setting"></i></a></li>
                                                          </ul>
                                                      </div>
                                                <div class="clear"></div>  
                                                </div>
                                                <div class="clear"></div>
                                           </div>
                                          </div>
                                    </div>
                                </div>
                    </div>
                    <div class="clear"> </div>
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                                                            <div class="learn-more-page">
                                                                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                                          <div class="modal-dialog">
                                                                            <div class="modal-content">
                                                                              <div class="modal-header">
                                                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                                                <h4 class="modal-title" id="myModalLabel">Help Center</h4>
                                                                              </div>
                                                                              <div class="modal-body">
                                                                                    <div class="duong-link"> 
                                                                                        <ol class="breadcrumb">
                                                                                          <li><a href="<?php echo $Editorapp ; ?> #">Help Center</a></li>
                                                                                          <li><a href="<?php echo $Editorapp ; ?> #">Pages</a></li>
                                                                                          <li class="active">Organizing Your Pages</li>
                                                                                          <div class="clear"> </div>
                                                                                        </ol>
                                                                                    </div>

                                                                                    <div class="link-youtube"> 
                                                                                        <div class="border-link-youtube"> 
                                                                                              
                                                                                            <img src="<?php echo $Editorapp ; ?>images/h19.png" class="img-responsive" alt="Responsive image">
                                                                                        </div>  
                                                                                    </div>
                                                                                    <div id="info-lear-more-a" class="scrollbar" >
                                                                                        <p>To organize your pages:</p>
                                                                                        <ul>
                                                                                            <li>Click the Pages icon.</li> 
                                                                                            <li>Drag and drop pages in the list to reorder them.</li>
                                                                                            <li>Click the page settings icon.</li>
                                                                                            <li>Type a name, hide, customize the SEO, duplicate or delete your page. Click Done.Your pages change.</li>
                                                                                        </ul> 
                                                                                        <p>To create a subpage, roll your mouse over the left side of a page on the list and drag the page to the right to turn it into a subpage. If your menu does not turn into a drop down </p>
                                                                                    </div>
                                                                                    <div class="clear"></div>
                                                                                    <div class="lear-more-infoma">
                                                                                        <a href="<?php echo $Editorapp ; ?> #"><span>Need more help? </span>Alatca support center</a>
                                                                                        <div class="clear"></div>
                                                                                    </div>
                                                                                <div class="clear"></div>
                                                                              </div>
                                                                               
                                                                            </div>

                                                                          </div>
                                                                          <div class="clear"></div> 
                                                                        </div>
                                                              </div>
                    
                    
                    
                    
                            
                    
                    
                    

<a data-toggle="modal" data-target="#myModal1" href="<?php echo $Editorapp ; ?> #">
  Launch demo modal
</a>
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Text</h4>
      </div>
      <div class="modal-body">
          <div class="content-add-text">
                <div class="add-text-top">
                       <div class="info-add-text">
                           <p>Choose the text you'd like to add to your site.</p>
                       </div>
                       <div class="lear-more-background-design">
                           <a href="<?php echo $Editorapp ; ?> #">Learn More</a>
                       </div>

                </div>
                <div class="add-text-center">
                    <div class="chon-add-text">
                            <div class="chon-tung-add-text">
                                <a href="<?php echo $Editorapp ; ?> #">Title</a>
                            </div> 
                            <div class="chon-tung-add-text">
                                <a href="<?php echo $Editorapp ; ?> #">Paragraph</a>
                            </div>
                    </div>                                             
                </div>
                
          </div>    
      </div>
      
    </div>
  </div>
</div>     











                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
            </div>
       	</div>
    </div>
    <script type="text/javascript" src="<?php echo $Editorapp ; ?>js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="<?php echo $Editorapp ; ?>js/bootstrap.min.js"></script>
        
</body>
</html>
