<?php 
	$editorappURL = $this->basePath('/editorapp/hairstyle/');
?>
<div id="body">
		<h3>hairstyles</h3>
		<ul>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle1.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle2.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle3.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle4.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle5.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle6.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle7.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle8.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle9.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle10.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle11.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle12.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle13.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle14.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle15.jpg" alt=""></a>
			</li>
			<li>
				<a href="#"><img src="<?php echo $editorappURL;?>/images/hairstyle16.jpg" alt=""></a>
			</li>
		</ul>
		<a href="#" class="more">show more</a>
	</div>