<?php
$title = 'Edit storydetail';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('storydetail', array('action' => 'edit', 'id'=>$this->id)));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formHidden($form->get('idmz')) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;

$img_content = $form->get('img');

//var_dump($img_content);

$tbl_img_label = $img_content->getOption('label');
//$txt_img_content = $img_content->getOption('value');
$txt_img_content = $this->formtext($img_content);
// $tbl_img_labelddd = $this->formimage();
// var_dump($tbl_img_labelddd);die;
//$img_src = $this->formImage($img_content);

?>
<div class="control-group">
		<label class="control-label" for=""><?php echo $tbl_img_label; //echo $this->translate($tbl_description, 'PerseedApplication');?></label>
		<div class="">
		<img alt="" src="<?php echo WEB_PATH_IMG.'/'.$txt_img_content ?>">  
		<?php echo $txt_img_content; ?>
		</div>
	</div>
	
<?php 
// echo $this->formRow($form->get('img')) . PHP_EOL;
// die;


$template_content = $form->get('description');
// var_dump($template_content);
// die;
$tbl_template_content = $template_content->getOption('label');
$txt_template_content = $this->formTextarea($template_content);

?>
<div class="control-group">
		<label class="control-label" for=""><?php echo $tbl_template_content; //echo $this->translate($tbl_description, 'PerseedApplication');?></label>
		<div class="controls">
			<?php echo $txt_template_content ;?>
		</div>
	</div>
	
<?php 



echo $this->formRow($form->get('page')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
<script type="text/javascript" src="<?php echo CKEDITOR_PATH;?>"></script>
<script type="text/javascript">
CKEDITOR.replace( 'description', {
	width: "900px",
	height: "300px",
	toolbar: "Full"
} );
</script>
