<?php
$title = 'My storydetail';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'artist')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>



<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php
echo $this->url('storydetail', array( 'action' => 'add'));
?>">Add new storydetail</a></p>


<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'title', 'order' => $url_order)); ?>">Title <?php if ($order_by == 'title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'description', 'order' => $url_order)); ?>">description <?php if ($order_by == 'description'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'img', 'order' => $url_order)); ?>">Thumbnail <?php if ($order_by == 'img'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th><a href="">Action</a></th>
    </tr>
    <?php foreach ($paginatorstory as $storydetail) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($storydetail->title); ?></td>
            <td><?php echo $this->escapeHtml($storydetail->description); ?></td>
            <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($storydetail->img); ?>" style="width: 100px; height:100px;"/></td>
            <td>
                <a href="<?php echo $this->url('storydetail', array('action' => 'edit', 'id' => $storydetail->id));
        ?>">Edit</a> |
                <a href="<?php echo $this->url('storydetail', array('action' => 'delete', 'id' => $storydetail->id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
   echo $this->paginationControl(
           $paginatorstory, 'Sliding', 'page-Storydetail', array('order_by' => $order_by, 'order' => $order)
   );
    ?>