<?php
$title = 'Add New Mzimg Detail';
$this->headTitle($title);

//echo 'Idmazinge';
//var_dump($this->id);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
    <tr>
        <th>
          <a href="">Title</a> 
        </th>
        <th>
          <a href="">description </a>  
        </th>
        <th>
          <a href="">Thumbnail</a>  
        </th>
        
        <th><a href="">Action</a></th>
    </tr>
    <?php foreach ($paginatorimg as $key =>$mzimg) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($mzimg['title']); ?></td>
            <td><?php echo $this->escapeHtml($mzimg['description']); ?></td>
            <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($mzimg['img']); ?>" style="width: 100px; height:100px;"/></td>
            <td>
                <a href="<?php echo $this->url('mzimg', array('action' => 'edit', 'id' => $mzimg['id']));
        ?>">Edit</a> |
                <a href="<?php echo $this->url('mzimg', array('action' => 'delete', 'id' => $mzimg['id']));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
//    echo $this->paginationControl(
//            $paginatorimg, 'Sliding', 'page-mzimg', array('order_by' => $order_by, 'order' => $order)
//    );
    ?>

    
    
<?php
$form = $this->form;
//$form->prepare();
$form->setAttribute('action', $this->url('newdetail', array('action' => 'adddetail')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formHidden($form->get('category_id')) . PHP_EOL;
echo $this->formHidden($form->get('user_id')) . PHP_EOL;
echo $this->formRow($form->get('name')) . PHP_EOL;
echo $this->formRow($form->get('brief')) . PHP_EOL;
echo $this->formRow($form->get('description')) . PHP_EOL;
echo $this->formRow($form->get('image_url')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

    

