
<h1>Upload File</h1>
<?php 

$form = $this->form;
$form->prepare();
?>


<?php echo $this->form()->openTag($form);?>

<ul>
	<li>

		<span><?php echo $this->formLabel($form->get('picture1')); ?></span>
		

		<?php echo $this->formElement($form->get('picture1')); ?>
	</li>
	<li>

		<span><?php echo $this->formLabel($form->get('picture2')); ?></span>
		
	
		<?php echo $this->formElement($form->get('picture2')); ?>
	</li>
	<li>
	
		<?php echo $this->formElement($form->get('submit'));?>
	</li>
</ul>


<?php echo $this->form()->closeTag() ?>