<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FileUpload\Module'                      => __DIR__ . '/Module.php',
    'FileUpload\Controller\Index'         => __DIR__ . '/src/FileUpload/Controller/Index.php',
    'FileUpload\Controller\Prg'      => __DIR__ . '/src/FileUpload/Controller/Prg.php',
    'FileUpload\Controller\Progress' => __DIR__ . '/src/FileUpload/Controller/Progress.php',
    'FileUpload\Form\CollectionUpload'       => __DIR__ . '/src/FileUpload/Form/CollectionUpload.php',
    'FileUpload\Form\FieldsetUpload'         => __DIR__ . '/src/FileUpload/Form/FieldsetUpload.php',
    'FileUpload\Form\MultiHtml5Upload'       => __DIR__ . '/src/FileUpload/Form/MultiHtml5Upload.php',
    'FileUpload\Form\ProgressUpload'         => __DIR__ . '/src/FileUpload/Form/ProgressUpload.php',
    'FileUpload\Form\SingleUpload'           => __DIR__ . '/src/FileUpload/Form/SingleUpload.php',
);