
<h1>Upload File</h1>
<?php 
//Lấy đối tượng Admin\Form\UploadForm từ trong VIEW ra
$form = $this->form;
$form->prepare();
?>

<!-- Tạo thẻ <form...> và các giá trị thuộc tính của thẻ này -->
<?php echo $this->form()->openTag($form);?>

<ul>
	<li>
		<!--In ra giá trị nhãn  -->
		<span><?php echo $this->formLabel($form->get('picture1')); ?></span>
		
		<!--Tạo phần tử HTML cho việc Upload -->
		<?php echo $this->formElement($form->get('picture1')); ?>
	</li>
	<li>
		<!--In ra giá trị nhãn  -->
		<span><?php echo $this->formLabel($form->get('picture2')); ?></span>
		
		<!--Tạo phần tử HTML cho việc Upload -->
		<?php echo $this->formElement($form->get('picture2')); ?>
	</li>
	<li>
		<!--Tạo nút Submit -->
		<?php echo $this->formElement($form->get('submit'));?>
	</li>
</ul>

<!-- Đóng thẻ </form> -->
<?php echo $this->form()->closeTag() ?>