<?php 
$title = 'My rssgets';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('rssget', array( 
        'action'=>'add'));?>">Add new rssget</a></p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($paginator as $rssget) : ?>
<tr>
    <td><?php echo $this->escapeHtml($rssget->title);?></td>
    <td><?php echo $this->escapeHtml($rssget->artist);?></td>
    <td>
        <a href="<?php echo $this->url('rssget',
            array('action'=>'edit', 'id' => $rssget->id));?>">Edit</a>
        <a href="<?php echo $this->url('rssget',
            array('action'=>'delete', 'id' => $rssget->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php 
echo $this->paginationControl(
            $paginator, 'Sliding', 'paginator-Rssget', array('order_by' => $order_by, 'order' => $order)
    );
?>