<?php 
$title = 'My mzimgs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('mzimg', array( 
        'action'=>'add'));?>">Add new mzimg</a></p>

<table class="table">
<tr>
    <th>img</th>
    <th>Description</th>
	<th>Title</th>
    <th>Action</th>
</tr>
<?php foreach($paginator as $mzimg) : ?>
<tr>
    <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($mzimg->img);?>" style="width: 100px; height:100px;"/></td>
    <td><?php echo $this->escapeHtml($mzimg->description);?></td>
	<td><?php echo $this->escapeHtml($mzimg->title);?></td>
    <td>
        <a href="<?php echo $this->url('mzimg',
            array('action'=>'edit', 'idmzalbum' => $mzimg->idmzalbum));?>">Edit</a>
        <a href="<?php echo $this->url('mzimg',
            array('action'=>'delete', 'idmzalbum' => $mzimg->idmzalbum));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php 
//echo $this->paginationControl(
//            $paginator, 'Sliding', 'paginator-mzimg', array('order_by' => $order_by, 'order' => $order)
//    );
?>