<?php
$title = 'Delete manastory';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHtml($manastory->title); ?>' by 
  '<?php echo $this->escapeHtml($manastory->descriptionkey); ?>'?
</p>
<?php 
$url = $this->url('manastory', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$manastory->id; ?>" />
  <input type="submit" name="del" value="Yes" class="btn btn-primary"/>
  <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>
