<?php
$title = 'My news';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'description')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>

<?php
$form  = $this->form;
$form->setAttribute('action', $this->url('news', array('action' => 'search')));
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) :
    ?>
    <div class="control-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <div class="controls">
            <?php
            echo $this->formElement($element);
            if ($this->formElementErrors($element)):
                ?>
                <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                <?php
            endif;
            ?>
        </div>
    </div>
    <?php
endforeach;
echo $this->form()->closeTag();
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a class="btn "  href="<?php
echo $this->url('news', array( 'action' => 'add'));
?>">Add new news</a></p>




<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('news', array('order_by' => 'name', 'order' => $url_order, 'search_by' => $search_by)); ?>">Name <?php if ($order_by == 'name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('news', array('order_by' => 'description', 'order' => $url_order, 'search_by' => $search_by)); ?>">description <?php if ($order_by == 'description'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('news', array('order_by' => 'img', 'order' => $url_order, 'search_by' => $search_by)); ?>">Thumbnail <?php if ($order_by == 'img'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th><a href="">Action</a></th>
    </tr>
    <?php foreach ($paginatorimg as $news) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($news->name); ?></td>
            <td><div><?php echo $news->description; ?></div></td>
            <td><img src="<?php echo Upload_NEWS.'/';?><?php echo $this->escapeHtml($news->image_url); ?>" style="width: 100px; height:100px;"/></td>
            <td>
                <a class="btn " href="<?php echo $this->url('news', array('action' => 'edit', 'id' => $news->id));
        ?>">Edit</a> 
                <a class="btn" href="<?php echo $this->url('news', array('action' => 'delete', 'id' => $news->id));
        ?>">Delete</a>
              
                  <?php
                    $delurl = $this->url('news', array (
                        'action' => 'delete',
                        'id'     => $news->id,
                    ));
                    ?>
                <!--    <div style="display: none;">
                        <form action="<?php echo $delurl; ?>" method="post" id="post_<?php echo $news->id; ?>" name="post_<?php echo $news->id; ?>">
                            <input type="hidden" name="id" value="<?php echo (int) $news->id; ?>" />
                        </form>
                    </div>
                    <a onclick="if (confirm('Are you sure you want to delete <?php echo $news->id; ?>?')) {document.<?php echo "post_" . $news->id; ?>.submit();} event.returnValue = false; return false;" href="#" class="btn btn-mini edit-row">Delete</a>
               -->  
            </td>
        </tr>
    <?php endforeach; ?>
</table>


<?php
   echo $this->paginationControl(
           $paginatorimg, 'Sliding', 'page-news', array('order_by' => $order_by, 'order' => $order , 'search_by' => $search_by, 'pageAction' => $pageAction)
   );


    ?>