<?php
$title = 'Add New news Detail';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php
$form = $this->form;
//$form->prepare();
$form->setAttribute('action', $this->url('news', array('action' => 'adddetail')));
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
if($this->id)
{
  echo $this->formHidden($form->get('category_id')) . PHP_EOL;
  }else {
	die('Oop Error .');
}
echo $this->formHidden($form->get('user_id')) . PHP_EOL;
echo $this->formRow($form->get('name')) . PHP_EOL;
echo $this->formRow($form->get('brief')) . PHP_EOL;
echo $this->formRow($form->get('description')) . PHP_EOL;
echo $this->formRow($form->get('image_url')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
<?php 
  
    if(!empty($paginatorimg))    
     {?>
     
     <table class="table">
	    <tr>
	        <th>
	          <a href="">Title</a> 
	        </th>
	        <th>
	          <a href="">description </a>  
	        </th>
	        <th>
	          <a href="">Thumbnail</a>  
	        </th>
	        
	        <th><a href="">Action</a></th>
	    </tr>
     
     <?php
     	   foreach ($paginatorimg as $key =>$news) : ?>
     	        <tr>
     	            <td><?php echo $this->escapeHtml($news['title']); ?></td>
     	            <td><?php echo $this->escapeHtml($news['description']); ?></td>
     	            <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($news['img']); ?>" style="width: 100px; height:100px;"/></td>
     	            <td>
     	                <a href="<?php echo $this->url('news', array('action' => 'edit', 'id' => $news['id']));
     	        ?>">Edit</a> |
     	                <a href="<?php echo $this->url('news', array('action' => 'delete', 'id' => $news['id']));
     	        ?>">Delete</a>
     	            </td>
     	        </tr>
     	    <?php endforeach;  
  ?>
   
    
     </table>

 <?php      } // end if?>

<?php
//    echo $this->paginationControl(
//            $paginatorimg, 'Sliding', 'page-news', array('order_by' => $order_by, 'order' => $order)
//    );
    ?>

    
    


