<?php
$title = 'Delete mzimg';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHtml($mzimg->title); ?>' by 
  '<?php echo $this->escapeHtml($mzimg->description); ?>'?
</p>
<?php 
$url = $this->url('mzimg', array('action' => 'delete', 'idmzalbum'=>$this->idmzalbum)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="idmzalbum" value="<?php echo (int)$mzimg->idmzalbum; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
