<?php
$title = 'My magazinepublishs';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'artist')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>
<?php 
// echo 'hang si '.WEB_PATH_IMG;
// echo '<br/>';
?>
<img src="<?php echo WEB_PATH_IMG;?>/book1/car_magazine_1.jpg" style="width: 50px;height:40px;">

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php
echo $this->url('magazinepublish', array(
    'action' => 'add'));
?>">Add new magazinepublish</a></p>


<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('magazinepublish', array('order_by' => 'title', 'order' => $url_order)); ?>">Title <?php if ($order_by == 'title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('magazinepublish', array('order_by' => 'descriptionkey', 'order' => $url_order)); ?>">description <?php if ($order_by == 'descriptionkey'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('magazinepublish', array('order_by' => 'imgkey', 'order' => $url_order)); ?>">Thumbnail <?php if ($order_by == 'imgkey'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th><a href="#">Action</a></th>
    </tr>
    <?php foreach ($paginator as $magazinepublish) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($magazinepublish->title); ?></td>
            <td><?php echo $this->escapeHtml($magazinepublish->descriptionkey); ?></td>
            <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($magazinepublish->imgkey); ?>" style="width: 100px; height:100px;"/></td>
            <td>
                <a href="<?php echo $this->url('magazinepublish', array('action' => 'edit', 'id' => $magazinepublish->id));
        ?>">Edit</a> |
                <a href="<?php echo $this->url('magazinepublish', array('action' => 'delete', 'id' => $magazinepublish->id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
    echo $this->paginationControl(
            $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order)
    );
    ?>