<?php
$title = 'Add new mgvndetail';
$this->headTitle($title);
//echo 'idmz view  ';var_dump($this->idmz);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
//$form->prepare();
$form->setAttribute('action', $this->url('mgvndetail', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formRow($form->get('idmz')) . PHP_EOL; // idmz = cataloguemagazine
echo $this->formRow($form->get('img')) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;

$template_content = $form->get('description');
$tbl_template_content = $template_content->getOption('label');
$txt_template_content = $this->formTextarea($template_content);

?>
<div class="control-group">
		<label class="control-label" for=""><?php echo $tbl_template_content; //echo $this->translate($tbl_description, 'PerseedApplication');?></label>
		<div class="controls">
			<?php echo $txt_template_content ;?>
		</div>
	</div>
	
<?php 



echo $this->formRow($form->get('page')) . PHP_EOL;
//echo $this->formRow($form->get('date')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

?>
<script type="text/javascript" src="<?php echo CKEDITOR_PATH;?>"></script>
<script type="text/javascript">
CKEDITOR.replace( 'description', {
	width: "900px",
	height: "300px",
	toolbar: "Full"
} );
</script>