<?php
$title = 'Delete mgvndetail';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete 
  '<?php echo $this->escapeHtml($mgvndetail->title); ?>' by 
  '<?php echo $mgvndetail->description; ?>'?
</p>
<?php 
$url = $this->url('mgvndetail', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$mgvndetail->id; ?>" />
  <input type="submit" name="del" value="Yes" class="btn btn-primary" />
  <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>
