<div class="box">
<div class="heading"><h1>Upload File and Unzip</h1></div>
<div class="form_field">
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('upload', array('action' => 'uploadnew')));
$form->prepare();
?>


<?php 
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('zip_file')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
</div>
</div>