<?php
$title = 'Delete manastory';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Select Delete Are you sure? If you delete the data will be erased and unrecoverable </p>
<?php 
$url = $this->url('manastory', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$manastory->id; ?>" />
  <input type="submit" name="del" value="Yes" class="btn btn-primary" />
  <input type="submit" name="del" value="No" class="btn btn-primary" />
</div>
</form>
