<?php
$title = 'Add New '.$this->namestory;
$this->headTitle($title);
?>

<?php 
if($this->id !== 0) 
 {?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
//$form->prepare();
$form->setAttribute('action', $this->url('storydetail', array('action' => 'adddetail')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formHidden($form->get('idmz')) . PHP_EOL;
echo $this->formRow($form->get('title')) . PHP_EOL;
echo $this->formRow($form->get('img')) . PHP_EOL;


$template_content = $form->get('description');
$tbl_template_content = $template_content->getOption('label');
$txt_template_content = $this->formTextarea($template_content);

?>
<div class="control-group">
		<label class="control-label" for=""><?php echo $tbl_template_content; //echo $this->translate($tbl_description, 'PerseedApplication');?></label>
		<div class="controls">
			<?php echo $txt_template_content ;?>
		</div>
	</div>
	
<?php 


echo $this->formRow($form->get('page')) . PHP_EOL;
//echo $this->formRow($form->get('date')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>

<?php
if (is_array($paginatorstory) and !empty($paginatorstory))
{
?>

<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'title', 'order' => $url_order)); ?>">Title <?php if ($order_by == 'title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'description', 'order' => $url_order)); ?>">description <?php if ($order_by == 'description'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'img', 'order' => $url_order)); ?>">Thumbnail <?php if ($order_by == 'img'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th><a href="">Action</a></th>
    </tr>
    <?php foreach ($paginatorstory as $storydetail) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($storydetail['title']); ?></td>
            <td><?php echo $this->escapeHtml($storydetail['description']); ?></td>
            <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($storydetail['img']); ?>" style="width: 100px; height:100px;"/></td>
            <td>
                <a class="btn " href="<?php echo $this->url('storydetail', array('action' => 'edit', 'id' => $storydetail['id']));
        ?>">Edit</a> 
                <a class="btn " href="<?php echo $this->url('storydetail', array('action' => 'delete', 'id' => $storydetail['id']));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
//    echo $this->paginationControl(
//            $paginatorstory, 'Sliding', 'page-Storydetail', array('order_by' => $order_by, 'order' => $order)
//    );
?>
<?php }// end check empty($paginatorstory)
   else
   { echo '<h3 style ="color: red;text-align: center;font-style: italic;"> Not have any books to display</h3>';} ?>
<?php 
 }
 else{
 	die('Oop! Error . ');
 }
?>

<script type="text/javascript" src="<?php echo CKEDITOR_PATH;?>"></script>
<script type="text/javascript">
	CKEDITOR.replace( 'description', {
		width: "900px",
		height: "300px",
		toolbar: "Full"
	} );
</script>