<?php
$title = 'My storydetail';
$this->headTitle($title);
$url_order = 'ASC';
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'description')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>

<h1>Search Storydetail </h1>
<?php
$form  = $this->form;
$form->setAttribute('action', $this->url('storydetail', array('action' => 'search')));
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) :
    ?>
    <div class="control-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <div class="controls">
            <?php
            echo $this->formElement($element);
            if ($this->formElementErrors($element)):
                ?>
                <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                <?php
            endif;
            ?>
        </div>
    </div>
    <?php
endforeach;
echo $this->form()->closeTag();
?>



<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a class="btn " href="<?php
echo $this->url('storydetail', array( 'action' => 'add'));
?>">Add new storydetail</a></p>


<table class="table">
    <tr>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'title', 'order' => $url_order, 'search_by' => $search_by)); ?>">Title <?php if ($order_by == 'title'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'description', 'order' => $url_order, 'search_by' => $search_by)); ?>">description <?php if ($order_by == 'description'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'img', 'order' => $url_order, 'search_by' => $search_by)); ?>">Thumbnail <?php if ($order_by == 'img'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
          <th>
            <a href="<?php echo $this->url('storydetail', array('order_by' => 'page', 'order' => $url_order,'search_by' => $search_by)); ?>">Page <?php if ($order_by == 'page'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th><a href="">Action</a></th>
    </tr>
    <?php foreach ($paginatorstory as $storydetail) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($storydetail->title); ?></td>
            <td><div> <?php echo $storydetail->description; ?></div></td>
            <td><img src="<?php echo WEB_PATH_IMG.'/';?><?php echo $this->escapeHtml($storydetail->img); ?>" style="width: 100px; height:100px;"/></td>
             <td><?php if($storydetail->page !== '') { ?><div>Page : <?php echo $storydetail->page; ?></div><?php }?></td>
            <td>
            <!--   <a class="btn " href="<?php echo $this->url('storydetail', array('action' => 'edit', 'id' => $storydetail->id));
        ?>">Edit</a> 
          --> 
                <a class="btn " href="<?php echo $this->url('storydetail', array('action' => 'delete', 'id' => $storydetail->id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
   echo $this->paginationControl(
           $paginatorstory, 'Sliding', 'page-Storydetail', array('order_by' => $order_by, 'order' => $order, 'search_by' => $search_by, 'pageAction' => $pageAction)
   );
    ?>