<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sMagazine Sevicer%s'), '<span class="zf-green">', '</span>') ?></h1>
   </div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Follow Development') ?></h2>
        <p>Data base being is update</p>
  </div>

    <div class="span4">
        <h2><?php echo $this->translate('Discover Modules') ?></h2>
        <p>Data base being is update</p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p>Data base being is update</p>
  </div>
</div>
