<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sMagazine Sevicer%s'), '<span class="zf-green">', '</span>') ?></h1>
   </div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Follow Development') ?></h2>
        <p>Data base being is update</p>
  </div>

    <div class="span4">
        <h2><?php echo $this->translate('Discover Modules') ?></h2>
        <p>Data base being is update</p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p>Data base being is update</p>
  </div>
</div>

<?php if($total_items > 0): ?>
<h3>Products in cart (<?php echo $total_items; ?>):</h3>
<table style="width: 900px;" border="1">
<tr>
  <th>Qty</th>
  <th>Name</th>
  <th>Item Price</th>
  <th>Sub-Total</th>
</tr>
<?php foreach($items as $key):?>
<tr>
    <td style="text-align: center;"><?php echo $key['qty']; ?></td>
    <td style="text-align: center;">
    <?php echo $key['name']; ?>
        <?php if($key['options'] != 0):?>
            Options:
            <?php foreach($key['options'] as $options => $value):?>
                <?php echo $options.' '.$value;?>
            <?php endforeach;?>
        <?php endif;?>
    </td>
    <td style="text-align: center;"><?php echo $key['price']; ?></td>
    <td style="text-align: center;"><?php echo $key['sub_total']; ?></td>
</tr>
<?php endforeach;?>
<tr>
  <td colspan="2"></td>
  <td style="text-align: center;"><strong>Sub Total</strong></td>
  <td style="text-align: center;"> <?php echo $total['sub-total'];?></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td style="text-align: center;"><strong>Vat</strong></td>
  <td style="text-align: center;"> <?php echo $total['vat'];?></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td style="text-align: center;"><strong>Total</strong></td>
  <td style="text-align: center;"> <?php echo $total['total'];?></td>
</tr>

<?php else: ?>
<h4>The Shopping Cart Empty</h4>
<?php endif;?>